In [22]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [25]:
df = pd.read_csv('/content/drive/MyDrive/house.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000
5  4100       6.0    8  810000

In [28]:
median_bedrooms = df.bedrooms.median()
print(median_bedrooms)

4.0


In [31]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000
5  4100       6.0    8  810000

In [33]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
reg.coef_

array([  114.65890296, 53376.41887759,  4767.23988188])

In [35]:
reg.intercept_

-36145.78849189263

In [38]:
reg.predict([[3000,4,15]])

array([592845.1941304])

In [39]:
import pickle

In [42]:
import os
cwd = os.getcwd()
print(cwd)

/content


In [41]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [46]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [47]:
mp.predict([[3000,4,15]])

array([592845.1941304])